// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB63OVQ8V2z-Hf0s3PHpnnw5axXj1-cWiY',
    appId: '1:1874141067:web:bef85a23c9bae445c5598e',
    messagingSenderId: '1874141067',
    projectId: 'stray-bookstore',
    authDomain: 'stray-bookstore.firebaseapp.com',
    storageBucket: 'stray-bookstore.firebasestorage.app',
    measurementId: 'G-2VG65XX5F4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5h9LYqmUtMeKIbh6HUE5fC8fpwnocW8o',
    appId: '1:1874141067:android:aac31d07e1fd0ce0c5598e',
    messagingSenderId: '1874141067',
    projectId: 'stray-bookstore',
    storageBucket: 'stray-bookstore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTSOApYFqe0cd98UN4y62G1vFYCl_MXn0',
    appId: '1:1874141067:ios:914919844868cb4dc5598e',
    messagingSenderId: '1874141067',
    projectId: 'stray-bookstore',
    storageBucket: 'stray-bookstore.firebasestorage.app',
    iosBundleId: 'com.example.strayBookstoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTSOApYFqe0cd98UN4y62G1vFYCl_MXn0',
    appId: '1:1874141067:ios:914919844868cb4dc5598e',
    messagingSenderId: '1874141067',
    projectId: 'stray-bookstore',
    storageBucket: 'stray-bookstore.firebasestorage.app',
    iosBundleId: 'com.example.strayBookstoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB63OVQ8V2z-Hf0s3PHpnnw5axXj1-cWiY',
    appId: '1:1874141067:web:f6e7405d7e345f46c5598e',
    messagingSenderId: '1874141067',
    projectId: 'stray-bookstore',
    authDomain: 'stray-bookstore.firebaseapp.com',
    storageBucket: 'stray-bookstore.firebasestorage.app',
    measurementId: 'G-WDHQDRNN8X',
  );
}
